name: "cilium"
version: "1.15.0-pre.2"
description: "eBPF-based Networking, Security, and Observability"
repository:
  sourcerefname: "cilium"
  url: "https://helm.cilium.io/"
valuesfrom:
  - overwritepath: ""
    defaultvalue: ""
    values: ""
  - overwritepath: ""
    defaultvalue: ""
    values: ""

  