name: "aws-for-fluent-bit"
version: "0.1.32"
description: "A Helm chart to deploy aws-for-fluent-bit project"
logoimageid: "713df283-63b6-498f-abf1-f0631c201511"
repository:
  sourcerefname: "aws"
  url: "https://aws.github.io/eks-charts"
valuesfrom:
  - overwritepath: "cloudWatch.enabled"
    defaultvalue: "false"
    values: ""
    description: "CloudWatch enabling" 

  - overwritepath: "cloudWatch.endpoint"
    defaultvalue: null
    values: ""
    description: "Specify a custom endpoint for the CloudWatch Logs API." 

  - overwritepath: "cloudWatch.logFormat"
    defaultvalue: null
    values: ""
    description: "An optional parameter that can be used to tell CloudWatch the format of the data. A value of json/emf enables CloudWatch to extract custom metrics embedded in a JSON payload"    
  
  - overwritepath: "cloudWatch.logStreamName"
    defaultvalue: null
    values: ""
    description: "The name of the CloudWatch Log Stream that you want log records sent to." 
  
  - overwritepath: "cloudWatch.logGroupName"
    defaultvalue: "/aws/eks/fluentbit-cloudwatch/logs"
    values: ""
    description: "The name of the CloudWatch Log Group that you want log records sent to."    
  
  - overwritepath: "cloudWatch.region"
    defaultvalue: "us-east-1"
    values: ""
    description: "The AWS region" 

  - overwritepath: "resources.limits.memory"
    defaultvalue: "250Mi"
    values: "1Gi"
    description: "Resource Limit Memory" 

  - overwritepath: "resources.requests.cpu"
    defaultvalue: "50m"
    values: "100m"
    description: "Resource Request CPU" 

  - overwritepath: "resources.requests.memory"
    defaultvalue: "50Mi"
    values: "100Mi"
    description: "Resource Request Memory" 

  - overwritepath: "s3.enabled"
    defaultvalue: "false"
    values: "true"
    description: "s3 bucket" 

  - overwritepath: "s3.bucket"
    defaultvalue: null
    values: ""
    description: "s3 Bucket name"

  - overwritepath: "s3.endpoint"
    defaultvalue: null
    values: ""
    description: "s3 Bucket Endpoint" 

  - overwritepath: "s3.region"
    defaultvalue: "us-east-1"
    values: ""
    description: "s3 Bucket Region" 

  - overwritepath: "s3.roleArn"
    defaultvalue: ""
    values: ""
    description: "s3 Bucket Role Arn" 

