name: "aws-for-fluent-bit"
version: "0.1.32"
description: "A Helm chart to deploy aws-for-fluent-bit project"
repository:
  sourcerefname: "aws"
  url: "https://aws.github.io/eks-charts"
valuesfrom:
  - overwritepath: "cloudWatch.enabled"
    defaultvalue: "false"
    values: "false"
    description: "CloudWatch enabling"    
  - overwritepath: "cloudWatch.endpoint"
    defaultvalue: null
    values: null
    description: "Specify a custom endpoint for the CloudWatch Logs API."  
  - overwritepath: "cloudWatch.logFormat"
    defaultvalue: null
    values: null
    description: "An optional parameter that can be used to tell CloudWatch the format of the data. A value of json/emf enables CloudWatch to extract custom metrics embedded in a JSON payload"    
  - overwritepath: "cloudWatch.logStreamName"
    defaultvalue: null
    values: null
    description: "The name of the CloudWatch Log Stream that you want log records sent to." 
  - overwritepath: "cloudWatch.logGroupName"
    defaultvalue: "/aws/eks/fluentbit-cloudwatch/logs"
    values: "/aws/eks/fluentbit-cloudwatch/logs"
    description: "The name of the CloudWatch Log Group that you want log records sent to."    
  - overwritepath: "cloudWatch.region"
    defaultvalue: "us-east-1"
    values: "us-east-1"
    description: "The AWS region." 
  - overwritepath: null
    values: null
    description: "The AWS region." 
  
  
  