displayname: "prometheus"
name: "prometheus"
version: "25.4.0"
description: "Prometheus is a monitoring system and time series database."
logoimageid: "0503add5-3fce-4b63-bbf3-b9f649512a86"
license: "Apache-2.0"
cloudformation_template: "https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/quickcreate?templateURL=https://cloudformation-test-bucket-curated.s3.amazonaws.com/ebs_attach_policy_stack.yaml&stackName=ebsAttachPolicyStack"
depends_on: ""
promocard_title: "Create role on AWS"
promocard_desc: "Create your role on AWS as its a mandatory step to create prometheus without Volume Persistance Claim error.If you already installed EBS CSI Driver addon and attach the policy in your Node Group ARN, or if you're not enabling persistent volume, you can skip this step."
documentaion_url: "https://stackoverflow.com/questions/50951515/persistent-volume-error-when-installing-prometheus-using-helm"
parameters: ["Node IAM role Name"]                                   
placeholders: ["initial-eks-node-group-202432040435200845000042001"]
info: ["Node Group IAM Role Name."]
repository:
  sourcerefname: "prometheus-community"
  url: "https://prometheus-community.github.io/helm-charts"
  verified_publisher: true
valuesfrom:
  - overwritepath: "prometheus-pushgateway.enabled"
    defaultvalue: "true"
    values: "false"
    description: "Enable Prometheus PushGateway"

  - overwritepath: "alertmanager.enabled"
    defaultvalue: "true"
    values: "false"
    description: "Enable Alert Manager"
  
  - overwritepath: "server.servicePort"
    defaultvalue: "80"
    values: "9090"
    description: "Server Service Port"

  - overwritepath: "server.persistentVolume.enabled"
    defaultvalue: "true"
    values: "false"
    description: "Enable Server Persistent Volume"
  
  - overwritepath: "server.ingress.enabled"
    defaultvalue: "false"
    values: "false"
    description: "Enable Server Ingress"

  

