displayname: "prometheus"
name: "prometheus"
version: "25.4.0"
description: "Prometheus is a monitoring system and time series database."
logoimageid: "0503add5-3fce-4b63-bbf3-b9f649512a86"
license: "Apache-2.0"
repository:
  sourcerefname: "prometheus-community"
  url: "https://prometheus-community.github.io/helm-charts"
  verified_publisher: true\
valuesfrom:
  - overwritepath: "prometheus-pushgateway.enabled"
    defaultvalue: "true"
    values: "false"
    description: "Enable Prometheus PushGateway"

  - overwritepath: "alertmanager.enabled"
    defaultvalue: "true"
    values: "false"
    description: "Enable Prometheus PushGateway"
  
  - overwritepath: "server.ingress.enabled"
    defaultvalue: "false"
    values: "true"
    description: "Enable Server Ingress"

  - overwritepath: "server.servicePort"
    defaultvalue: "80"
    values: "9090"
    description: "Server Service Port"

  

