name: "prometheus"
version: "25.4.0"
description: "Prometheus is a monitoring system and time series database."
repository:
  sourcerefname: "prometheus-community"
  url: "https://prometheus-community.github.io/helm-charts"
valuesfrom:
  - overwritepath: "server.replicaCount"
    defaultvalue: "1"
    values: "1"