name: "grafana"
version: "7.0.3"
description: "The leading tool for querying and visualizing time series and metrics."
repository:
  sourcerefname: "grafana"
  url: "https://grafana.github.io/helm-charts"
valuesfrom:
  - overwritepath: ""
    defaultvalue: ""
    values: ""
  - overwritepath: ""
    defaultvalue: ""
    values: ""
  
  