name: "aws-cloudwatch-metrics"
version: "0.0.9"
description: "A Helm chart to deploy aws-cloudwatch-metrics project"
repository:
  sourcerefname: "aws"
  url: "https://aws.github.io/eks-charts"
valuesfrom:
  - overwritepath: "clusterName"
    defaultvalue: ""
    values: ""
    description: "Cluster Name"   

  - overwritepath: "resources.limits.cpu"
    defaultvalue: "200m"
    values: "200m"
    description: "CPU limit"  

  - overwritepath: "resources.limits.memory"
    defaultvalue: "200Mi"
    values: "200Mi"
    description: "Memory limit"    

  - overwritepath: "resources.requests.cpu"
    defaultvalue: "200m"
    values: "200m"
    description: "Requests CPU"  

  - overwritepath: "resources.requests.memory"
    defaultvalue: "200Mi"
    values: "200Mi"
    description: "Requests Memory"    

  - overwritepath: "serviceAccount.create"
    defaultvalue: "true"
    values: "true"
    description: "service Account create"    
  
  - overwritepath: "serviceAccount.name"
    defaultvalue: "null"
    values: ""
    description: "service Account create"   

  - overwritepath: "statsd.enabled"
    defaultvalue: "false"
    values: "false"
    description: "statsd enabled"   

  - overwritepath: "statsd.port"
    defaultvalue: "8125"
    values: "8125"
    description: "statsd port"   

  - overwritepath: "statsd.protocol"
    defaultvalue: "UDP"
    values: "UDP"
    description: "statsd protocol"   