name: "aws-cloudwatch-metrics"
version: "0.0.9"
description: "A Helm chart to deploy aws-cloudwatch-metrics project"
repository:
  sourcerefname: "aws"
  url: "https://aws.github.io/eks-charts"
valuesfrom:
  - overwritepath: "clusterName"
    defaultvalue: ""
    values: ""
    description: "Cluster Name"   

  - overwritepath: "resources.limits.cpu"
    defaultvalue: "200m"
    values: ""
    description: "CPU limit"  

  - overwritepath: "resources.limits.memory"
    defaultvalue: "200Mi"
    values: ""
    description: "Memory limit"    

  - overwritepath: "resources.requests.cpu"
    defaultvalue: "200m"
    values: ""
    description: "Requests CPU"  

  - overwritepath: "resources.requests.memory"
    defaultvalue: "200Mi"
    values: ""
    description: "Requests Memory"    
