name: "aws-for-fluent-bit"
version: "0.1.32"
description: "A Helm chart to deploy aws-for-fluent-bit project"
logoimageid: "713df283-63b6-498f-abf1-f0631c201511"
license: "Apache-2.0"
repository:
  sourcerefname: "aws"
  url: "https://aws.github.io/eks-charts"
  verified_publisher: false
valuesfrom:
  - overwritepath: "cloudWatchLogs.logGroupName"
    defaultvalue: "/aws/eks/fluentbit-cloudwatch/logs"
    values: ""
    description: "CloudWatch Logs Logs Group Name" 

  - overwritepath: "cloudWatchLogs.region"
    defaultvalue: "us-east-1"
    values: "us-east-1"
    description: "CloudWatch Logs Region" 

  - overwritepath: "resources.limits.memory"
    defaultvalue: "250Mi"
    values: "1Gi"
    description: "Resource Limit Memory" 

  - overwritepath: "resources.requests.cpu"
    defaultvalue: "50m"
    values: "100m"
    description: "Resource Request CPU" 

  - overwritepath: "resources.requests.memory"
    defaultvalue: "50Mi"
    values: "100Mi"
    description: "Resource Request Memory" 

  - overwritepath: "s3.enabled"
    defaultvalue: "false"
    values: "true"
    description: "s3 Bucket Enabled" 

  - overwritepath: "s3.bucket"
    defaultvalue: "dev-eks-s3-bucket"
    values: ""
    description: "s3 Bucket Name"

  - overwritepath: "s3.region"
    defaultvalue: "us-east-1"
    values: ""
    description: "s3 Bucket Region" 
    
secrets:
  - overwritepath: "s3.roleArn"
    defaultvalue: "arn:aws:iam::123456789012:role/s3-access-role"
    values: ""
    description: "s3 Bucket Role Arn" 

  - overwritepath: "cloudWatchLogs.roleArn"
    defaultvalue: arn:aws:iam::123456789012:role/s3-access-role"
    values: ""
    description: "CloudWatch Logs Role ARN" 

