name: "external-dns"
version: "6.28.4"
description: "ExternalDNS is a Kubernetes addon that configures public DNS servers with information about exposed Kubernetes services to make them discoverable."
repository:
  sourcerefname: "bitnami"
  url: "https://charts.bitnami.com/bitnami"
valuesfrom:
  - overwritepath: ""
    defaultvalue: ""
    values: ""
  - overwritepath: ""
    defaultvalue: ""
    values: ""
