name: "prometheus"
version: "25.4.0"
description: "Prometheus is a monitoring system and time series database."
repository:
  sourcerefname: "prometheus-community"
  url: "https://prometheus-community.github.io/helm-charts"
values:
  serviceAccounts:
    server:
      annotations:
        eks.amazonaws.com/role-arn: "${IAM_PROXY_PROMETHEUS_ROLE_ARN}"

valuesfrom:
  - overwritepath: "serviceAccounts.server.name"
    defaultvalue: ""
    values: "amp-iamproxy-ingest-service-account"
    description: "Service Account Name"

  - overwritepath: "server.remoteWrite.url"
    defaultvalue: ""
    values: "https://aps-workspaces.${REGION}.amazonaws.com/workspaces/${WORKSPACE_ID}/api/v1/remote_write"
    description: "Remote Write URL"

  - overwritepath: "server.remoteWrite.signv4.region"
    defaultvalue: ""
    values: "${REGION}"
    description: "Region"

  - overwritepath: "server.remoteWrite.queue_config.max_samples_per_send"
    defaultvalue: ""
    values: "1000"
    description: "Queue Config Max per Samples per Send"

  - overwritepath: "server.remoteWrite.queue_config.max_shards"
    defaultvalue: ""
    values: "200"
    description: "Queue Config Max Shards"

  - overwritepath: "server.remoteWrite.queue_config.capacity"
    defaultvalue: ""
    values: "2500"
    description: "Queue Config Capacity"

  - overwritepath: "prometheus-pushgateway.enabled"
    defaultvalue: true
    values: false
    description: "prometheus-pushgateway enabled" 

  - overwritepath: "alertmanager.enabled"
    defaultvalue: true
    values: false
    description: "alertmanager enabled" 
    
  - overwritepath: "server.priorityClassName"
    defaultvalue: ""
    values: "infra-high-priority"
    description: "priority ClassName" 

  - overwritepath: "server.ingress.enabled"
    defaultvalue: false
    values: true
    description: "Ingress enabled" 

  - overwritepath: "server.persistentVolume.enabled"
    defaultvalue: true
    values: false
    description: "persistent Volume" 

  - overwritepath: "server.global.scrape_interval"
    defaultvalue: "1m"
    values: "30s"
    description: "global scrape_interval" 

  - overwritepath: "server.statefulSet.enabled"
    defaultvalue: false
    values: false
    description: "statefulSet Enabled" 

  - overwritepath: "server.service.servicePort"
    defaultvalue: 80
    values: 9090
    description: "statefulSet Enabled" 

  - overwritepath: "server.service.servicePort"
    defaultvalue: 80
    values: 9090
    description: "statefulSet Enabled" 
   
  
  
  